version: 2
jobs:
  build:
    branches:
      only:
        - typescript
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - run: npm install
      - run: cd deployment/pollurl && npm install && cd ../..
      - run: npm run test