version: 2
jobs:
  build:
    branches:
      only:
        - master
        - new-file-layout
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - run: npm install
      - run: npm run test:unit
      - run: npm run test:e2e
