version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm run test:unit
      - run: npm run test:e2e
