version: 2
jobs:
  build:
    docker:
      - image: cypress/included:5.6.0
        entrypoint: /bin/bash
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - store_artifacts: 
          path: /root/project/cypress/screenshots
          destination: screenshots